#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScreenCapture.Resource", IsApplication=true)]

namespace ScreenCapture
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CommonSampleLibrary.Resource.String.library_name = global::ScreenCapture.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F010000
			public const int horizontal_page_margin = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int margin_huge = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int margin_large = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int margin_medium = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int margin_small = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int margin_tiny = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int vertical_page_margin = 2130771974;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int tile = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int log_fragment = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int menu_toggle_log = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int sample_content_fragment = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int sample_main_layout = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int sample_output = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int surface = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int toggle = 2130903046;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int fragment_screen_capture = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int intro_message = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int library_name = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int sample_hide_log = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int sample_show_log = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int start = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int stop = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int user_cancelled = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int Theme_Base = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int Theme_Sample = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int Widget = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int Widget_SampleMessage = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int Widget_SampleMessageTile = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
